### ISSUE TITLE
return subnet id for jumbox and agent subnet 

### ISSUE THREAD

**Issue by ahmedsza** [cykreng/Enterprise-Scale-AppService#11]
@cenkms 
Need the networking module to return the subnet id that can be used in the shared module for the devops agent and the jumpbox

**Comment by cenkms** [comment]
@ahmedsza I believe it should be good right now, plese take a look and let me know.

**Comment by ahmedsza** [comment]
@cenkms  - I don't see the ids being returned. I see the names but not the id.. Can you advise on what call i need to make in main.bicep to get the subnet id

**Comment by ahmedsza** [comment]
id are being returned now. Thanks @cenkms . Closing
