### ISSUE TITLE
Setup Bastion

### ISSUE THREAD

**Issue by ahmedsza** [cykreng/Enterprise-Scale-AppService#31]
Looks like a bastion subnet is setup but not the actual service..

**Comment by hkamel** [comment]
I'm checking this issue and seems it's not related to the network setting as I see Bastion host configured. It's related to the networking configuration (Bicep file).

**Comment by ahmedsza** [comment]
I ran the main.bicep - and don't see the bastion service. So if I goto a VM and try to connect I see this
![image](https://user-images.githubusercontent.com/37135205/129699041-9bcea54e-5cf2-4b51-a9ce-09b9c0038111.png)

and then if I click that button it takes me to the screen to set it 
@cenkms  - do you know if Bastion is setup.

**Comment by hkamel** [comment]
I'm running the PowerShell for the first time and can't find the link between network settings and the main file may be missing something. I'm referring basically to those two files https://github.com/cykreng/Enterprise-Scale-AppService/tree/main/deployment/bicep/vnettest

**Comment by ahmedsza** [comment]
the vnettest was setup by me when we did not have the proper networking module in place.. It was a placeholder - as I needed the networking to be in place in order to create the VMs. 

I left it in the repo but we should consider removing it if it will cause confusion. the real networking is taking place in https://github.com/cykreng/Enterprise-Scale-AppService/blob/main/deployment/bicep/networking.bicep

The bits in vnettest does have the code to setup bastion...

**Comment by hkamel** [comment]
Clear, thanks. can you assign this issue to me? I will get the Bastion setup done.

**Comment by hkamel** [comment]
This now implemented ... I will follow with a PR
![image](https://user-images.githubusercontent.com/5002831/129743771-17b97341-c3aa-453b-ba1a-53c1ff7d3fe3.png)
